CREATE TABLE [dbo].[AppAccesses]
(
	[ID] BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[UserID] INT NOT NULL,
	[AppID] INT NOT NULL,
	[HasAccess] BIT NOT NULL DEFAULT 1,
    CONSTRAINT [FK_AppAccesses_UserID] FOREIGN KEY ([UserID]) REFERENCES [Users]([ID]) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT [FK_AppAccesses_AppID] FOREIGN KEY ([AppID]) REFERENCES [Apps]([ID]) ON UPDATE CASCADE ON DELETE CASCADE
)
