CREATE TABLE [dbo].[AppVersions]
(
	[ID] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[AppID] INT NOT NULL,
	[Name] VARCHAR(50) NOT NULL,
	[ExeID] BIGINT NULL,
	[ReportURL] VARCHAR(1000) NULL,
	[Changelog] VARCHAR(MAX) NULL,
	[AuthorID] INT NOT NULL,
	[CreateDT] DATETIME NOT NULL DEFAULT GETDATE(),
	[CreatedBy] INT NOT NULL,
	[ModifyDT] DATETIME NOT NULL DEFAULT GETDATE(),
	[ModifiedBy] INT NOT NULL,
    CONSTRAINT [FK_AppVersions_AppID] FOREIGN KEY ([AppID]) REFERENCES [Apps]([ID]) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT [FK_AppVersions_ExeID] FOREIGN KEY ([ExeID]) REFERENCES [AppFiles]([ID]) ON UPDATE CASCADE ON DELETE SET NULL
)
