CREATE TABLE [dbo].[GroupMembers]
(
	[ID] BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[UserID] INT NOT NULL,
	[GroupID] INT NOT NULL,
    CONSTRAINT [FK_GroupMembers_UserID] FOREIGN KEY ([UserID]) REFERENCES [Users]([ID]) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT [FK_GroupMembers_GroupID] FOREIGN KEY ([GroupID]) REFERENCES [Users]([ID]) ON UPDATE CASCADE ON DELETE CASCADE
)
