CREATE TABLE [dbo].[Logs]
(
	[ID] BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[UserID] INT NULL,
	[VersionID] INT NULL,
	[Type] VARCHAR(1) NOT NULL,
	[Content] VARCHAR(2000) NOT NULL,
	[CreateDT] DATETIME NOT NULL DEFAULT GETDATE()
    CONSTRAINT [FK_Logs_UserID] FOREIGN KEY ([UserID]) REFERENCES [Users]([ID]) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT [FK_Logs_VersionID] FOREIGN KEY ([VersionID]) REFERENCES [AppVersions]([ID]) ON UPDATE CASCADE ON DELETE CASCADE
)
