CREATE TABLE [dbo].[Properties]
(
	[ID] BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[AppID] INT NOT NULL,
	[UserID] INT NULL,
	[Name] VARCHAR(100) NOT NULL,
	[Value] VARCHAR(100) NOT NULL,
	[ActivationDT] DATETIME NULL DEFAULT GETDATE(),
	[IsPermission] BIT NOT NULL DEFAULT 0,
    CONSTRAINT [FK_Properties_AppID] FOREIGN KEY ([AppID]) REFERENCES [Apps]([ID]) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT [FK_Properties_UserID] FOREIGN KEY ([UserID]) REFERENCES [Users]([ID]) ON UPDATE CASCADE ON DELETE CASCADE
)
