CREATE TABLE [dbo].[Users]
(
	[ID] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Name] VARCHAR(100) NOT NULL,
	[FirstName] VARCHAR(100) NULL,
	[LastName] VARCHAR(100) NULL,
	[Email] VARCHAR(100) NULL,
	[IsAdmin] BIT NOT NULL DEFAULT 0,
	[IsGroup] BIT NOT NULL DEFAULT 0
)
